config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/home', to: 'pages#home'

  devise_for :users, controllers: { registrations: 'registrations' }

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  resources :deliverers, only: %i[index new create edit update show]
  resources :shifts, only: %i[index new create edit update]

  resources :assignments, only: %i[index new create]
end

app/views/pages/_shift_assignment_form.html.erb
<div>
  <h3>Shifts Assignment</h3>

  <%= bootstrap_form_for(@assignment) do |f| %>
    <%= f.select :deliverer_id, @deliverers.map{ |d| ["#{d.id} - #{d.name}", d.id] } %>
    <%= f.select :shift_id, @shifts.map{ |s| ["#{s.id} - #{s.start_time_to_s}", s.id] } %>

    <%= f.submit 'Assign Shift', class: 'btn sign-up-button' %>
  <% end %>
</div>

app/views/pages/_view_assignment_form.html.erb
<div>
  <h3>View Assignment</h3>

  <%= bootstrap_form_for(@assignment, :url => assignments_show_path) do |f| %>

    <table>
      <tr>
        <td><strong>From</strong></td>
        <td><strong>To</strong></td>
      </tr>
      <tr>
        <td><%= date_select 'range1', 'date', :order => [:day, :month, :year] %></td>
        <td><%= date_select 'range2', 'date', :order => [:day, :month, :year] %></td>
      </tr>
    </table>

    <%= f.submit 'Search', class: 'btn sign-up-button' %>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-offset-2 col-md-8">

      <h2>Shift Assignment Dashboard</h2>

      <%= render "shared/flash_messages" %>

    </div>
  </div>

  <div class="row bottom-buffer">
    <div class="col-md-offset-2 col-md-8">

      <div class="panel-group top-buffer">
        <div class="panel panel-default">
          <div class="panel-heading">
            <strong>Deliverer</strong>
          </div>
          <div class="panel-body">
              <ul>
                <li><a href="deliverers">View all</a></li>
                <li><a href="deliverers/new">Create deliverer</a></li>
              </ul>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">
            <strong>Shift</strong>
          </div>
          <div class="panel-body">
            <ul>
              <li><a href="shifts">View all</a></li>
              <li><a href="shifts/new">Create shift</a></li>
            </ul>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">
            <strong>Assignment</strong>
          </div>
          <div class="panel-body">
            <ul>
              <li><a href="assignments">View all</a></li>
              <li><a href="assignments/new">Create assignment</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/info.html.erb
<div class="container">
  <div class="row">
  <div class="col-md-offset-4 col-md-4">

    <h1>All deliverers</h1>

    <table>
      <tr>
        <td><strong>Name</strong></td>
        <td><strong>Phone</strong></td>
        <td><strong>Vehicle</strong></td>
        <td><strong>Status</strong></td>
      </tr>
      <% @deliverers.each do |deliverer| %>
        <tr>
          <td><%= link_to deliverer.name, edit_deliverer_path(deliverer) %></td>
          <td><%= deliverer.phone %></td>
          <td><%= vehicle_helper deliverer.vehicle %></td>
          <td><%= active_helper deliverer.active %></td>
        </tr>
      <% end %>
    </table>
    <br>
    <%= button_to "Create new Deliverer", new_deliverer_path, :method => "get",
        class: "btn sign-up-button"%>

  <h1>All shifts</h1>

  <table>
    <tr>
      <td><strong>Start Time</strong></td>
      <td><strong>End Time</strong></td>
      <td><strong>Max Count</strong></td>
    </tr>
    <% @shifts.each do |shift| %>
      <tr>
        <td><%= link_to shift.start_time, edit_shift_path(shift) %></td>
        <td><%= shift.end_time %></td>
        <td><%= shift.max_count %></td>
      </tr>
    <% end %>
  </table>
  <br>
  <%= button_to "Create new Shift", new_shift_path, :method => "get",
      class: "btn sign-up-button"%>
</div>
</div>
</div>